// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: models/authentication.proto

package models

var AuthenticationHttpServerDescriptor = &HttpServerDescriptor{
	Name: "authentication",
	Routes: []*RouteDescriptor{

		{
			GrpcMethod:  "Login",
			Url:         "/login",
			Method:      "post",
			IsWebSocket: false,
		},

		{
			GrpcMethod:  "CreateUser",
			Url:         "/user",
			Method:      "post",
			IsWebSocket: false,
		},

		{
			GrpcMethod:  "KeepAlive",
			Url:         "/keep_alive",
			Method:      "",
			IsWebSocket: true,
		},
	},
}
