// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: models/blog.proto

package models

var BlogHttpServerDescriptor = &HttpServerDescriptor{
	Name: "blog",
	Routes: []*RouteDescriptor{

		{
			GrpcMethod:  "CreateArticle",
			Url:         "/article",
			Method:      "post",
			IsWebSocket: false,
		},
	},
}
